- project:
    name: openstack/puppet-tripleo
    templates:
      - puppet-openstack-check-jobs
    check:
      jobs:
        - puppet-openstack-unit-4.8-centos-7
        - puppet-openstack-unit-latest-centos-7
    gate:
      jobs:
        - puppet-openstack-unit-4.8-centos-7
